### ISSUE TITLE
New diagnostics mode

### ISSUE THREAD

**Issue by thradams** [thradams/cake#112]
The idea is to create the concept of diagnostic. User will decide if a message will be an error, warning or note.
Se have 3 sets.
error,warning, note

if the diagnostic message is not on any of these sets, that means the message is ignored.

**Comment by mingodad** [comment]
For completeness I propose to also add `pedantic` as a more strict mode.

**Comment by thradams** [comment]
Also a way to remove the message from the context. It can be minus sign.

```c
#pragma warning set "no-ownwership-checks" "-241, -454"

#pragma warning push "no-ownwership-checks"
//
#pragma warning pop

```

**Comment by thradams** [comment]
```c
void F(int i);
_Owner int make();
int main()
{
    F(make());

#pragma cake diagnostic check "-Wnon-owner-move"
}
```

new pragma added for unit test.if the last diagnostic is the one informed then the error ir cleared.
otherwise an error is added.
at the end with this pragma unit test must return no errors.
all unit tests must use this.

**Comment by thradams** [comment]
#pragma cake diagnostic check "-Wnon-owner-move" works well for problem in preprocessor and compiler but will not work um analizer . mybe static_state.
but then we have two ways; static_state will no work in preprocessor.

**Comment by thradams** [comment]
implemented like GCC the only difference is ignore note , that is something below warning.
