### ISSUE TITLE
Missing checks for uninitialized object

### ISSUE THREAD

**Issue by thradams** [thradams/cake#126]
```c
struct Z{
  int dummy;
};

struct Y{
  int dummy;
  struct Z * _Owner pZ;
};

struct X{
  struct Y * _Owner pY;
};
struct X * _Owner newX();
void deleteX(struct X* _Owner p);
void f(struct Z* p);

int main(){
  struct X * _Owner p = newX();
  deleteX(p);
  f(p->pY->pZ);
}
```
This is the state of p
```
c:/main.c:20:3: note: static_debug
 20 |  static_debug(p);
    |  ^~~~~~~~~~~~
 p == "uninitialized"
  p->pY == "uninitialized"
```
The problem is that when we have pY uninitialized then p->pY->pZ  should be an error even if we don't have the pZ state.

**Comment by mingodad** [comment]
Why got too further when showing an error at `p->` is more than enough (I mean the first one in sequence is good enough).

**Comment by thradams** [comment]
Missing the same for DOT etc.. ++ -- etc..

**Comment by thradams** [comment]
Sample where it necessary a deep pointed to pointed ... 
but instead of create a big "tree" the data struct that hold these values can be modified to something like a map that only have the state that is checked and a default value for others.
In this sample when 

```
  deleteZ(p->pY->pZ);
```
we annotate "->pY ->pZ" is uninitialized.

imagine a deeper structure.
we annotate "pU->pX->pY->pZ" is uninitialized.

```c
struct Z{
  int dummy;
};

struct Y{
  int dummy;
  struct Z * _Owner pZ;
};

struct X{
  struct Y * _Owner pY;
};
struct X * _Owner newX();
void deleteX(struct X* _Owner p);
void deleteZ(struct Z* _Owner p);
void f(struct Z* p);

int main(){
  struct X * _Owner p = newX();
  deleteZ(p->pY->pZ);
  f(p->pY->pZ); //fails today because pZ state is not present.
}
```

**Comment by mingodad** [comment]
Again as I said before it seems that in a sequence we can stop at the first invalid access (I assume that you are recursively verifying each pointer access).

**Comment by mingodad** [comment]
And it's still doesn't catch this https://github.com/thradams/cake/issues/115#issuecomment-1963914031

**Comment by thradams** [comment]
> Again as I said before it seems that in a sequence we can stop at the first invalid access (I assume that you are recursively verifying each pointer access).

I agree.

The problem with deep states is something this.

Imagine a linked list

```c
free(p->next->next->next->next->next->next);
use(p->next->next->next->next->next->next);
```

it is an open design problem.. 
how or if cake will track this.
today it has 2 pointed objects for each and a check for recursion.

**Comment by mingodad** [comment]
Let's start by having a function to dump the parse tree to help debug the parser.

**Comment by mingodad** [comment]
Something like what's here https://mingodad.github.io/parsertl-playground/playground/ (select any example from `Examples` then click `Parse` to see the parse tree for the content in `Input source`).

**Comment by thradams** [comment]
To dump an AST a new "visit" can be created.

**Comment by thradams** [comment]
working.
```c
#pragma safety enable
struct Z{
  int dummy;
};

struct Y{
  int dummy;
  struct Z * _Owner pZ;
};

struct X{
  struct Y * _Owner pY;
};
struct X * _Owner newX();
void deleteX(struct X* _Owner p);
void f(struct Z* p);

int main(){
  struct X * _Owner p = newX();
  deleteX(p);
  f(p->pY->pZ);
}
```
