### ISSUE TITLE
Support MinGW compiler

### ISSUE THREAD

**Issue by 3oheicrw-alter-ego** [thradams/cake#13]
From `build.h` it seems you program doesn't support MinGW compiler. MinGW usually used with the GCC compiler, but there are MinGW based LLVM Clang like this too: https://github.com/mstorsjo/llvm-mingw/releases

You only covered MSVC and MSVC based LLVM Clang. You left out the entire MinGW based world.

**Comment by 3oheicrw-alter-ego** [comment]
Not to mention, you left out Cygwin, too.

**Comment by thradams** [comment]
Yes. I am using only gcc on linux and msvc on windows. 
I will check clang and write instructions how to add new platforms.

Basically, we use the same compiler used to compile build.c to generate cake. (except emscripten)
The compiler/platform is detected ate build.h using ifdefs and then at build.c the command line
is selected. You can try adding a new platform.

'''c

#if defined(_WIN32) && defined(_MSC_VER) && !defined(__clang__)
#define BUILD_WINDOWS
#define BUILD_WINDOWS_MSC
#define COMPILER_NAME "cl"
#define RUN ""
#elif defined(_WIN32) && defined(__clang__)
#define BUILD_WINDOWS
#define BUILD_WINDOWS_CLANG
#define RUN ""
#define COMPILER_NAME "clang"
#elif defined(__linux__) && defined(__clang__)
#define BUILD_LINUX
#define BUILD_LINUX_CLANG
#define COMPILER_NAME "clang"
#define RUN "./"
#elif defined(__linux__) && defined(__GNUC__)
#define BUILD_LINUX
#define BUILD_LINUX_GCC
#define COMPILER_NAME "gcc"
#define RUN "./"
#else
#error Unknown Platform/Compiler
#endif
'''
Then at build.c we call the appropriated command line. For instance:

'''c
#ifdef BUILD_LINUX_CLANG
    system("clang "
           SOURCE_FILES " main.c "
#ifdef TEST
           "-DTEST"
#endif
           " -std=c17 "
           " -Wall "
           " -o " OUTPUT);
#endif
'''
