### ISSUE TITLE
dynamic macros __COUNT__ __LINE__ __FILE__ are not being expanded correctly

### ISSUE THREAD

**Issue by thradams** [thradams/cake#135]
dynamic macros __COUNT__ __LINE__ __FILE__ are not being expanded correctly

**Comment by thradams** [comment]
missing unit test

**Comment by iphydf** [comment]
It seems `__FILE__` is now expanded without quotes, so it gives a bunch of syntax errors when used.

**Comment by thradams** [comment]
I think it is fixed.

**Comment by thradams** [comment]
sizeof must return 0 for empty structs.
