### ISSUE TITLE
`sizeof(uint16_t) == 4)` but it should be 2.

### ISSUE THREAD

**Issue by iphydf** [thradams/cake#140]
```c
static_assert(sizeof(uint16_t) == 4, "this should not pass (but does)");
static_assert(sizeof(uint16_t) == 2, "this should pass (but does not)");
```

I'm guessing `uint16_t` expands to `unsigned int`, which is ok on some really old targets, but not on x86_64, where it should be `unsigned short`.

**Comment by thradams** [comment]
the problem was on sizeof short, the code was using int.
fixed in the previous commit with a lot of sizeof errors.
