### ISSUE TITLE
VLA support missing

### ISSUE THREAD

**Issue by iphydf** [thradams/cake#143]
Since https://github.com/thradams/cake/commit/426413d8ee7d1413a9a287590c1a62d3ceae5a25

```c
int a;
int b() {
  char c[a];
}
```

This is not an error in C99 (or C23, which cake targets).

**Comment by thradams** [comment]
I will change the title broken to missing because it was not implemented.
at manual there is a list of other features not implemented yet.

**Comment by thradams** [comment]
the idea is not implement VLA and just variable modified types.
input
```c
#include <stdlib.h>
#include <stdio.h>

int main() {
    int n = 2;
    int m = 3;
    int (*p)[n][m] = malloc(sizeof * p);

    printf("%zu\n", sizeof(*p));

    free(p);
}
```
output could be

```c
#include <stdlib.h>
#include <stdio.h>

int main() {
    int n = 2;
    int m = 3;
    
    /*these variables are created to store the dynamic size*/
    const int vla_1_n = n;
    const int vla_1_m = m;
    
    int (*p)[n][m] = malloc((vla_1_n*vla_1_m)*sizeof(int));

    printf("%zu\n", (vla_1_n*vla_1_m)*sizeof(int));

    free(p);
}

```

**Comment by iphydf** [comment]
Before the new error it was at least ignored, so it was "working" in a way. Now, cake can no longer parse/type check code that it used to be able to.

**Comment by thradams** [comment]
ok! I think you are talking about this one

```
 error: error: storage size of 'c' isn't known
 ```
 I will remove the error, check VLA and add a note.
