### ISSUE TITLE
[P2] `sizeof(union)` is computed incorrectly

### ISSUE THREAD

**Issue by iphydf** [thradams/cake#145]
```c
union Foo {
    char a;
    char b;
};

static_assert(sizeof(union Foo) == 1);  // fails
```

It seems that `sizeof` is calculated the same for `union` as for `struct` (`sum` of the member sizes), but it should be a `max` of all the member sizes.

**Comment by thradams** [comment]
missing unit tests with unions.

**Comment by thradams** [comment]
the unit test could be better.. but at least I have one.
