### ISSUE TITLE
[P1] Segmentation fault on `-fanalyzer`

### ISSUE THREAD

**Issue by iphydf** [thradams/cake#146]
crash.c:
```c
struct a {
  char b;
} c;
void d() {
  struct a e = c;
}
```

Invocation: `cake -fanalyzer crash.c`

Segfault happens here: https://github.com/thradams/cake/blob/e322139e9d493c2c7b9f9614037a5e5b569bd69e/src/object.c#L633

```
#22 0.968 Program received signal SIGSEGV, Segmentation fault.
#22 0.968 0x000000000041cd2e in set_object_state (ctx=ctx@entry=0x7fffb7a76810, p_type=p_type@entry=0x7fd0819df190, p_object=p_object@entry=0x7fd0819df158, p_source_type=p_source_type@entry=0x7fffb7a76110, p_object_source=p_object_source@entry=0x7fd0819d9a88, error_position=error_position@entry=0x7fd0819f62f0) at object.c:633
#22 0.968 633	                                set_object_state(ctx,
```

**Comment by iphydf** [comment]
Another segfault, I didn't check if it's the same root cause:

```c
#include <ownership.h>

typedef struct Foo {
    int *owner p;
} Foo;

Foo *owner foo_new(void) {
    Foo *owner foo = (Foo *owner)calloc(1, sizeof(Foo));

    if (foo == NULL) {
        return NULL;
    }

    return foo;
}
```

**Comment by thradams** [comment]
The static variables state were not begin tracked. 

```c
struct a {
  char b;
} c;
void d() {
  struct a e = c;
}
```
here is the plan...
initialize the global variables at declaration. if it is const the state if fixed in all the program.
if the it is not const, each time we enter in a function the state will be "unknown" at the begging of the function.
not sure how to implement. maybe at first usage inside the function make it "unknown" then i put in a list "already used".

**Comment by iphydf** [comment]
Cool, then the second one is a separate bug.

**Comment by thradams** [comment]
this sample also needs attention

```c
void d() {
  static struct a {  char b;} c;
  struct a e = c;
}
```

**Comment by thradams** [comment]
I fixed the segmentation fault,
 but the state of global variables still wrong. I need to reset the state of global variables.

**Comment by thradams** [comment]
created
 global variables with -fanalyzer #150

**Comment by thradams** [comment]
segmentation fault fixed
