### ISSUE TITLE
Incorrect diagnostic: assignment to expression with array type

### ISSUE THREAD

**Issue by iphydf** [thradams/cake#149]
```c
void foo(char x[10]) {
    char y[10];
    x = y;                                                                                                                                  
}
```

This should be fine. `x` is actually a pointer parameter, and `y` can decay to a pointer. It's useful for static analysis to treat the `[10]` as array in some cases, but this assignment should be allowed.

**Comment by thradams** [comment]
Actually this was on purpose.. but in this case I may change the category instead of warning "note".

**Comment by iphydf** [comment]
I guess that makes sense. Assigning params is a bad idea anyway. I'll refactor my code. No need to fix this.

**Comment by thradams** [comment]
```
int main(){
  int a[2];
  int b[2];
  a = b; //this is where the error is correct.
}
```

**Comment by iphydf** [comment]
Yes, that's a 100% correct error because that code is invalid. In the parameter case, it's valid C code, but I'd argue nobody should write that code. It's better to have a local pointer variable and assign the parameter to that.
