### ISSUE TITLE
unknown warning '-Wno-conditional-constant'

### ISSUE THREAD

**Issue by iphydf** [thradams/cake#154]
I get:
```
#14 0.907 /src/workspace/c-toxcore/toxcore/DHT.c:2822:13: warning: conditional expression is constant [-Wconditional-constant]
```

But I don't seem to be able to disable it with `-Wno-conditional-constant`.

**Comment by thradams** [comment]
`#if ?`

**Comment by iphydf** [comment]
It's `if (LOG_LEVEL_INFO >= LOG_LEVEL_TRACE)` which comes from a logging macro.

**Comment by thradams** [comment]
if LOG_LEVEL_INFO and LOG_LEVEL_TRACE are macros then 

```c
#if (LOG_LEVEL_INFO >= LOG_LEVEL_TRACE)
#endif
```

**Comment by iphydf** [comment]
They are enums, not macros. Also this is from a macro expansion like `LOGGER_TRACE(msg, ...)`.

**Comment by iphydf** [comment]
https://github.com/TokTok/c-toxcore/blob/master/toxcore%2Flogger.h#L81

**Comment by thradams** [comment]
At command like 
```
cake -Wno-conditional-constant
```

or

```c
enum {A, B};
int main(){
#pragma cake diagnostic push
#pragma cake diagnostic ignored "-Wconditional-constant"
    if (B > A){}
#pragma cake diagnostic pop
}

```

**Comment by iphydf** [comment]
If I try the first option, I get:

```
1.278 unknown warning '-Wno-conditional-constant'
1.278  0 files in 0.00 seconds
1.278  0 errors 0 warnings 0 notes 
```

The second option isn't an option for me.
