### ISSUE TITLE
build does not work on macos

### ISSUE THREAD

**Issue by bentxt** [thradams/cake#196]
macos 14.5 (23F79)

```
clang -dumpversion
12.0.1
```

### Potentially interesting errors:

```
44 1 warning generated.
45 In file included from tokenizer.c:58:
46 In file included from ./fs.h:87:
47 /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/dirent.h:84:3: error: typedef redefinition with different       types ('struct DIR' vs 'struct __dirstream')
 48 } DIR;
 ```

```
 868 error.c:7:9: warning: unknown pragma ignored [-Wunknown-pragmas]
 869 #pragma safety enable
 870         ^
 871 error.c:187:11: error: use of undeclared identifier 'ECHRNG'
 872     case  ECHRNG:
 873           ^
 874 error.c:189:11: error: use of undeclared identifier 'EL2NSYNC'
 875     case  EL2NSYNC:
...
```

### Logfile 

The entire err.log of `build` is attached here: [err.log](https://github.com/user-attachments/files/16677764/err.log)

**Comment by thradams** [comment]
The errors  seems easy to fix , but I don't have mac to test right now. 
(The build on mac has never been tested)
The windows linux are automated. (I don't know if is possible to automatite build on macos on git actions)

**Comment by bentxt** [comment]
Can I do something to help?

**Comment by mingodad** [comment]
Github actions seems to have OSX runners
