### ISSUE TITLE
clang compile fails due to DT_DIR undefined

### ISSUE THREAD

**Issue by gtoal** [thradams/cake#202]
This needs to be added to the linux clang build options:

diff build.c*
250d249
<            " -D_DEFAULT_SOURCE"

**Comment by thradams** [comment]
Thanks, fix added. I also added at readme.md

Apart of that, for some reason

```c
           " -Wno-unknown-pragmas "
           " -Wno-multichar "
```
is not working on clang.

**Comment by thradams** [comment]
found the problem.. -Wall must be before the -Wno..
