### ISSUE TITLE
Several compiler warnings/errors when building on Ubuntu 18.04 with gcc9

### ISSUE THREAD

**Issue by mingodad** [thradams/cake#208]
After a fresh clone of this repository and following the instructions on the README I'm getting several warnings/erros (see attached).
```
gcc build.c -o build && ./build > make.log 2>&1
```
[make.log.zip](https://github.com/user-attachments/files/17702680/make.log.zip)

**Comment by thradams** [comment]
(The last github action worked on linux.)
https://github.com/thradams/cake/actions

**Comment by thradams** [comment]
I can see a regression.

```c
extern struct X x;
```

It is complaining the size is unknown but for extern this is not necessary.

**Comment by mingodad** [comment]
Look here https://github.com/mingodad/cake/actions/runs/11782635827/job/32818097430 on Ubuntu-20-04 there is several warnings (running `gcc -o build build.c && ./build` notice no `-DTEST` just in case it matters).

**Comment by mingodad** [comment]
Looking at both it seems that you are not fixing the warnings emitted by `cake` over itself.

**Comment by mingodad** [comment]
On Ubuntu-18.04 we have this on `<stdio.h>`:
test-stdio.c:
```
#include <stdio.h>
```
Output:
```
gcc -E test-stdio.c
# 1 "test-stdio.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "test-stdio.c"
# 1 "/usr/include/stdio.h" 1 3 4
# 27 "/usr/include/stdio.h" 3 4
...
# 36 "/usr/include/x86_64-linux-gnu/bits/libio.h" 2 3 4
# 53 "/usr/include/x86_64-linux-gnu/bits/libio.h" 3 4

typedef struct _IO_FILE _IO_FILE;


struct _IO_FILE_plus;

extern struct _IO_FILE_plus _IO_2_1_stdin_;
extern struct _IO_FILE_plus _IO_2_1_stdout_;
extern struct _IO_FILE_plus _IO_2_1_stderr_;
...
```
And cake outputs this error:
```
/usr/include/x86_64-linux-gnu/bits/libio.h:319:29: error: storage size of '_IO_2_1_stdin_' isn't known E1270]
 319 |extern struct _IO_FILE_plus _IO_2_1_stdin_;
     |                            ~~~~~~~~~~~~~~  
/usr/include/x86_64-linux-gnu/bits/libio.h:320:29: error: storage size of '_IO_2_1_stdout_' isn't known E1270]
 320 |extern struct _IO_FILE_plus _IO_2_1_stdout_;
     |                            ~~~~~~~~~~~~~~~  
/usr/include/x86_64-linux-gnu/bits/libio.h:321:29: error: storage size of '_IO_2_1_stderr_' isn't known E1270]
 321 |extern struct _IO_FILE_plus _IO_2_1_stderr_;
     |                            ~~~~~~~~~~~~~~~  
...
```

**Comment by thradams** [comment]
> Looking at both it seems that you are not fixing the warnings emitted by `cake` over itself.

The explosion of warning is caused when enabling nullable checks. (#pragma safety enable)
I was fixing all the warnings (more than 1000) that weren't problems in the static analysis. (true warnings)
The remaining number of warnings was around 450, many of of them something I need to fix in the static analyzer.
One problem was initialization (designed initializer etc).
So now, I am fixing initialization  and at same time I am fixing/generalizing constexpr.
The next step is fix initialization in flow analysis. them I expect to reduce to less than 450 warnings and resume warning removal.

To see "normal" C compiler warning you can comment `#pragma safety enable`

**Comment by thradams** [comment]
The problem E1270 has been identified I will commit it soon.
Basically remove the error when the variable has the storage qualifiers extern.

**Comment by thradams** [comment]
extern error fixed

**Comment by mingodad** [comment]
Thank you for reply and fix it !

It's now dying with this message:
```
Cake 0.9.32
file '/tmp/cake/src/cakeconfig.h'
successfully generated
./cake  -fanalyzer  console.h  tokenizer.h  parser.h  error.h  fs.h  flow_object.h  hashmap.h  osstream.h  options.h  token.h  type.h  pre_expressions.h  object.h  expressions.h  visit.h  format_visit.h  token.c  hashmap.c  console.c  tokenizer.c  osstream.c  fs.c  options.c  object.c  expressions.c  pre_expressions.c  flow_object.c  parser.c  visit.c  flow_visit.c  error.c  format_visit.c  type.c 
cake: object.c:1551: make_object_ptr_core: Assertion `p_last_member_obj->next != NULL' failed.
Aborted
```
Now looking at the non `cake` specific warnings there is this:
```
tokenizer.c: In function ‘include_config_header’:
tokenizer.c:5223:14: warning: passing argument 1 to restrict-qualified parameter aliases with argument 4 [-Wrestrict]
 5223 |     snprintf(local_cakeconfig_path, sizeof local_cakeconfig_path, "%s" CAKE_CFG_FNAME, local_cakeconfig_path);
      |              ^~~~~~~~~~~~~~~~~~~~~                                                     ~~~~~~~~~~~~~~~~~~~~~
tokenizer.c:5223:67: warning: ‘/cakeconfig.h’ directive output may be truncated writing 13 bytes into a region of size between 1 and 500 [-Wformat-truncation=]
 5223 |     snprintf(local_cakeconfig_path, sizeof local_cakeconfig_path, "%s" CAKE_CFG_FNAME, local_cakeconfig_path);
      |                                                                   ^~~~
In file included from tokenizer.c:62:
tokenizer.h:13:25: note: format string is defined here
   13 | #define CAKE_CFG_FNAME "/cakeconfig.h"
      |                         ^~~~~~~~~~~~~
tokenizer.c:5223:5: note: ‘snprintf’ output between 14 and 513 bytes into a destination of size 500
 5223 |     snprintf(local_cakeconfig_path, sizeof local_cakeconfig_path, "%s" CAKE_CFG_FNAME, local_cakeconfig_path);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
That can be fixed by this:
```
int include_config_header(struct preprocessor_ctx* ctx, const char* file_name)
     snprintf(local_cakeconfig_path, sizeof local_cakeconfig_path, "%s", file_name);
     dirname(local_cakeconfig_path);
 
-    snprintf(local_cakeconfig_path, sizeof local_cakeconfig_path, "%s" CAKE_CFG_FNAME, local_cakeconfig_path);
+    snprintf(local_cakeconfig_path, sizeof local_cakeconfig_path, "%s" CAKE_CFG_FNAME, file_name);
 
     char* _Owner _Opt str = read_file(local_cakeconfig_path, true);
     while (str == NULL)
```
Another:
```
parser.c: In function ‘designation_to_string’:
parser.c:10448:17: warning: passing argument 1 to restrict-qualified parameter aliases with argument 4 [-Wrestrict]
10448 |                 snprintf(buffer, sz, "%s[%llu]", buffer, index);
      |                 ^~~~~~~~
parser.c:10453:17: warning: passing argument 1 to restrict-qualified parameter aliases with argument 4 [-Wrestrict]
10453 |                 snprintf(buffer, sz, "%s.%s", buffer, designator->token->lexeme);
      |                 ^~~~~~~~
```
Can be fixed with something like this:
```
static void designation_to_string(struct parser_ctx* ctx, struct designation* designation, char buffer[], int sz)
 {
     buffer[0] = '\0';//out
+    int buf_offset = 0;
     try
     {
         struct designator* _Opt designator = designation->designator_list->head;
@@ -10445,13 +10446,16 @@ static void designation_to_string(struct parser_ctx* ctx, struct designation* de
                 unsigned long long index =
                     object_to_unsigned_long_long(&designator->constant_expression_opt->object);
 
-                snprintf(buffer, sz, "%s[%llu]", buffer, index);
+                buf_offset += snprintf(buffer + buf_offset, sz-buf_offset, "[%llu]", index);
             }
             else if (designator->token)
             {
-                //TODO diminiar sz
-                snprintf(buffer, sz, "%s.%s", buffer, designator->token->lexeme);
+                buf_offset += snprintf(buffer + buf_offset, sz-buf_offset, ".%s", designator->token->lexeme);
             }
+	    if(buf_offset >= sz)
+	    {
+                compiler_diagnostic_message(C_ERROR_UNEXPECTED, ctx, ctx->current, NULL, "designation_to_string buffer too small");
+	    }
 
             designator = designator->next;
         }
```

**Comment by mingodad** [comment]
Looking through the code in `tokenizer.c::test_preprocessor_in_out` it seems that there is no need to allocate an empty string and leak it:
https://github.com/thradams/cake/blob/f6b9e2ad7e1d1a94031f40d541560c7e3eaa3023/src/tokenizer.c#L6327-L6332
We can use `result = "";` instead.

**Comment by mingodad** [comment]
Also memory usage is a bit high 249MB compared to `gcc` 39MB (6x) , `clang` 90MB  (2.7x) when processing `sqlite3.c`:
```
/usr/bin/time cake -E sqlite3.c  > /dev/null
0.71user 0.11system 0:00.83elapsed 99%CPU (0avgtext+0avgdata 249444maxresident)k
0inputs+0outputs (0major+61974minor)pagefaults 0swaps

/usr/bin/time gcc -E sqlite3.c  > /dev/null
0.15user 0.03system 0:00.19elapsed 100%CPU (0avgtext+0avgdata 39388maxresident)k
0inputs+0outputs (0major+8498minor)pagefaults 0swaps

clang-19-env /usr/bin/time clang -E sqlite3.c  > /dev/null
0.13user 0.01system 0:00.15elapsed 96%CPU (0avgtext+0avgdata 90548maxresident)k
168inputs+0outputs (1major+4776minor)pagefaults 0swaps
```

**Comment by thradams** [comment]
> Also memory usage is a bit high 249MB compared to `gcc` 39MB (6x) , `clang` 90MB (2.7x) when processing `sqlite3.c`:
> 
> ```
> /usr/bin/time cake -E sqlite3.c  > /dev/null
> 0.71user 0.11system 0:00.83elapsed 99%CPU (0avgtext+0avgdata 249444maxresident)k
> 0inputs+0outputs (0major+61974minor)pagefaults 0swaps
> 
> /usr/bin/time gcc -E sqlite3.c  > /dev/null
> 0.15user 0.03system 0:00.19elapsed 100%CPU (0avgtext+0avgdata 39388maxresident)k
> 0inputs+0outputs (0major+8498minor)pagefaults 0swaps
> 
> clang-19-env /usr/bin/time clang -E sqlite3.c  > /dev/null
> 0.13user 0.01system 0:00.15elapsed 96%CPU (0avgtext+0avgdata 90548maxresident)k
> 168inputs+0outputs (1major+4776minor)pagefaults 0swaps
> ```

I believe the deference is caused by the spaces/comments that are necessary to rebuild the output source.
I also keep comments from the included files (that are not visible) and these spaces can be removed.
The reason I kept the comments from included files is to allow someone uses comments as "special"  tokens.
For instance, I know some static analyzers that disable warnings with especial comments. So, keeping the comments inside the AST could allow that. But this is not used today. Also, we  now have attributes that could work for this task.
So maybe I could remove this part or at lease make an option to ignore comments/spaces from included files and another option ignore comments/spaces from the main file and in this case the output is 100% reformatted. (Maybe another option to keep comments :D, like typescript)

Apart of that, another way I could save memory is to put strings in a map? So we wouldn't have duplicates like "int"everywhere.

**Comment by thradams** [comment]
linux build working
