### ISSUE TITLE
Can't select targets: Unknown option -target

### ISSUE THREAD

**Issue by trholding** [thradams/cake#214]
The target options aren't working:

```
./cake -target
Cake 0.9.38
unknown option '-target'
 0 files in 0.00 seconds
 0 errors 0 warnings 0 notes 

./cake -target=c99 
Cake 0.9.38
unknown option '-target=c99'
 0 files in 0.00 seconds
 0 errors 0 warnings 0 notes 

./cake -target=c89
Cake 0.9.38
unknown option '-target=c89'
 0 files in 0.00 seconds
 0 errors 0 warnings 0 notes 
```

Related: https://github.com/thradams/cake/discussions/213

**Comment by thradams** [comment]
This mode, which I call 'edit mode,' has been removed in the latest versions. The documentation has been updated to reflect this, but I still need to update a few remaining sections.
At readme for instance I updated.

See use cases

"Previous versions of Cake included a conversion mode to translate code while preserving the preprocessor parts. Although useful, this process could not guarantee 100% conversion, functioning more as a tool than a compiler. With the new versions of Cake moving toward becoming a more traditional compiler, the previous mode has been discontinued at version 0.9.36. This version is online here http://thradams.com/cake3/playground.html."

The particular file that does this conversion was visit.c

Reasons to remove it include
   - Cannot generated for some items like has_include
   - It is another mode to maintain alongside other components
   - This mode is hard to get 100% precision and difficult to maintain. 
      It works by 'editing' user code, and this process must account for macros
   - Increases the size of the AST compared with normal compiler mode.
          
   It still possible to bring this mode back or even be a separated part.
The new mode (and the only mode is c89)  but it is more than that, is is generated as it it was a intermediated language being low level. It is desiged to be used as pipeline and then discard.

c23 source ->cake->out->CC->exe


Let me know your toughs and needs.

**Comment by thradams** [comment]
The command line is new just

cake source.c

since there is only one mode. or 

cake source.c -no-output 

to works as static analyzer without generated code.

**Comment by trholding** [comment]
It would be cool if you could support edit mode or create it as an alternate tool, meanwhile I'll try to build an older version and see.

My use case was to transpile loose c99 (with a bit of non c99) code to ANSI C / C 89 to port some tools to vintage CRAY COS with ack compiler. My code was not too complex only that it needed to be converted to C89.

A similar tool I came across was https://github.com/libav/c99-to-c89  , but that one is pretty outdated.

So edit mode can be pretty useful for people who port stuff to retro computers or who have to maintain stuff.

One thing I noticed is that cake processes all header files and in the out dir you find sort of an amalgamated c file.

If there was an option just to take a in C file and output c89 or c99 without touching includes and ifdefs, it would be cool.

For example I had some hobby cases where I ported stuff to retro with vbcc, and gcc. gcc would be build the project fine with very little changes but vbcc would complain that its not pure c99 at it is lowest c89.

So if you consider making a alt cake fork with https://github.com/libav/c99-to-c89  like functionality and without processing includes / headers, it would be cool and soon would become a popular choice for retro coders. Usually libc for target is available and amalgamating host includes would fail to build for or on target systems. 

> This mode is hard to get 100% precision and difficult to maintain.
It is understood that transpiling to C89 would be hard and sometimes some things won't be possible but if it can output what it can do and comment in code what it couldn't get done, it still would be of immense use. When porting, one has to anyways add or change stuff.

I really appreciate the reply and the hard work you put into your project! Awesome tool.

**Comment by trholding** [comment]
I checked the Edit version and it does good transpiling... but https://github.com/davidgiven/ack with ack -ansi still complains about lot of stuff...  like this:

```
ack -ansi main.c 
"main.c", line 261: identifier missing before {
"main.c", line 261: identifier missing before .
"main.c", line 261: ; missing before }
"main.c", line 262: identifier missing before {
"main.c", line 262: identifier missing before .
"main.c", line 262: ; missing before }
"main.c", line 307: ; missing before int
"main.c", line 307: < deleted
"main.c", line 308: identifier missing before type_identifier
"main.c", line 321: ; missing before int
"main.c", line 321: < deleted
"main.c", line 325: ; missing before int
"main.c", line 325: < deleted
"main.c", line 326: x undefined
"main.c", line 326: identifier missing before type_identifier
"main.c", line 334: -> deleted
"main.c", line 337: < deleted
"main.c", line 338: identifier missing before type_identifier
"main.c", line 339: quantized not in parameter list
"main.c", line 339: illegal initialization of formal parameter
"main.c", line 339: (warning) implicit declaration of function round
"main.c", line 339: (warning) round is a function; cannot be formal
"main.c", line 339: round not in parameter list
"main.c", line 340: x is not a type identifier
"main.c", line 340: -> deleted
"main.c", line 349: ; missing before int
"main.c", line 349: < deleted
"main.c", line 351: p undefined
"main.c", line 351: p not in parameter list
"main.c", line 352: p is not a type identifier
"main.c", line 352: = deleted
"main.c", line 354: identifier missing before type_identifier
"main.c", line 354: identifier missing before type_identifier
"main.c", line 357: (strict) declaration specifiers missing
"main.c", line 357: p undefined
"main.c", line 358: return deleted
"main.c", line 403: : missing before *
"main.c", line 403: (strict) illegal conversion of pointer to int
"main.c", line 406: : missing before identifier
"main.c", line 411: } missing before int
"main.c", line 411: illegal initialization
"main.c", line 412: += deleted
"main.c", line 413: if deleted
"main.c", line 418: sizeof deleted
"main.c", line 422: illegal initialization
"main.c", line 423: += deleted
"main.c", line 425: illegal initialization
"main.c", line 426: += deleted
"main.c", line 430: (strict) declaration specifiers missing
```

**Comment by thradams** [comment]
The objective of C89 in previous versions "edit mode" was to have a version compatible with C++.
But it had some missing features like no translation of compound literals, anonymous structs etc.

In the new version the objective is to have a low level and simple version of C , compatible with C89, to work as IL.

The advantage of previous mode was to distribute source. 
The new mode will work much better but the objective is direct compilation then discard.
source -> cake -> c89 compatible -> CC

For this task cake need to use the same headers used by CC.  
(Something missing in the new mode is reposition declarations at top of compound literals.)

**Comment by trholding** [comment]
Thank you. I am closing this as c89 edit mode is depreciated.
