### ISSUE TITLE
__VA_OPT__ only seems to work if there is __VA_ARGS__ in the replacement

### ISSUE THREAD

**Issue by gustedt** [thradams/cake#34]
I'd expect the following macro to work

```C
 #define empty(...) (__VA_OPT__(!)1)
```

And to result in `(1)` if called with no arguments and `(!1)` when called with arguments. Instead the expansion is `(__VA_OPT__(!)1)` in both cases.

**Comment by thradams** [comment]
Added a sample that show remaining problems with __VA_OPT__

**Comment by thradams** [comment]
All VA_OPT problems fixed !
