### ISSUE TITLE
constness troubles

### ISSUE THREAD

**Issue by gustedt** [thradams/cake#35]
Qualifiers seem to be treated quite wrongly

```C
int main()
{
   double const x = 78.9;
   double y = 78.9;
   auto q = x;
   auto const p = &x;
   auto const r = &y;
}
```

Here this results in `q` being `const double`, which is wrong because the initializer is undergoing lvalue conversion and looses qualification.

`p` and `r` are even worse, because the `const` doesn't land on the right side of the `*` as it should. The `const` in an `auto` declaration applies to the whole type on the RHS, much as if it where encapsulated in a `typedef`.

**Comment by thradams** [comment]
What is the correct code generation of : ?

```c
int main()
{
   double const x = 78.9;
   double y = 78.9;
   auto q = x;
   auto const p = &x;
   auto const r = &y;
}
```
Cake is generating (after fixes)

```c
int main()
{
   double const x = 78.9;
   double y = 78.9;
   double   q = x;
   double   * const p = &x;
   double   * const r = &y;
}
```

**Comment by gustedt** [comment]
Much better!
But unfortunately the line for `p` is wrong. It should be one of

```C
double const*const p = &x;
const double*const p = &x;
```

Which are equivalent.  (I personally prefer the first, but that's a matter of taste and habits.)

There is no lvalue conversion for the operands to the following operators

- `sizeof`
- `alignof`
- `typeof`
- `typeof_unqual` (but which looses the qualifiers)
- `&`
- the chosen expression of a `_Generic`

(I hope I didn't forget any)

**Comment by thradams** [comment]
Cake is now generating 


```c
   //
   double const x = 78.9;
   double y = 78.9;
   auto q = x;
   auto const p = &x;
   auto const r = &y;
```

```c
  double const x = 78.9;
  double y = 78.9;
  double   q = x;
  const double const  * p = &x;
  double const  * r = &y;
```
But I confess i am not sure if the solution is general. Maybe it is.

(
One design decision I made is to not make lvalue conversions until the "last minute" 
when needed. This may be a cause of this confusion with auto initialization.
I may regret this decision, but the idea is to have all type information for static analysis.
For instance if I try this on gcc -Wall
```c
"123"[10];
```
it does not show any warning, but the index is bigger than the array.
I am not checking this error, but because I have the complete type information it is easy to do.

)

**Comment by thradams** [comment]
I tried with gcc 
````c
int main()
{
    double A[3] = { 0 };
    auto pA = &A;
    (*pA)[1] = 3;
}
```
https://godbolt.org/z/hfbn7zj4T

Cake is generating (I guess it is correct)

```c
int main()
{
    double A[3] = { 0 };
    double  (* pA)[3] = &A;
    (*pA)[1] = 3;
}
```

**Comment by gustedt** [comment]
> Cake is now generating
> 
> ```c
>    //
>    double const x = 78.9;
>    double y = 78.9;
>    auto q = x;
>    auto const p = &x;
>    auto const r = &y;
> ```
> 
> ```c
>   double const x = 78.9;
>   double y = 78.9;
>   double   q = x;
>   const double const  * p = &x;
>   double const  * r = &y;
> ```
> 
> But I confess i am not sure if the solution is general. Maybe it is.

That is unfortunately still wrong for `p` and `r`. It seems to me that you have the output of types and their qualifiers in the wrong order. If you first output the type and only then the qualifier all would be well.

The solution above for `p` just applies the `const` to `double` twice, which is redundant. If you'd invert the output order this would lead to 

```C
double const* const p = &x;
double * const r = &y;
```

which is correct.

The problem is perhaps easier to see when using different qualifiers

```C
   double const x = 78.9;
   double y = 78.9;
   auto q = x;
   auto restrict p = &x;
   auto restrict r = &y;
```

Here the current output for `p` is

```C
const double restrict* p = &x;
```
which isn't even correct C (any dialiect) because `restrict` only applies to pointer types.

**Comment by thradams** [comment]
I opened #37 for non-conforming problems of auto . I am comparing against GCC.

**Comment by thradams** [comment]
If specifiers have const then after lvalue conversion we make the type const.

```c
int a[3];
const auto const  const p = &x;
```
Generates

```c
int a[3];
double  * const p = &x;
```
With "address of" we don´t do any lvalue conversion just make const if required.

**Comment by thradams** [comment]
I will close this and if necessary problems of auto can be mentioned in 37.
