### ISSUE TITLE
C23 auto

### ISSUE THREAD

**Issue by thradams** [thradams/cake#37]
With this sample

```c
int main() {
 int a5[5];
 auto a[3] = &a5;
}
```
GCC emits
error: 'auto' requires a plain identifier, possibly with attributes, as declarator

Cake generates (similar what happens with typedefs)

```c
int main()
{
 int a5[5];
 int  (* a[3])[5] = &a5;
}
```
Also

```c
int main()
{
 int * p2;
 auto * p2 = p1;
}
```

GCC 
error: 'auto' requires a plain identifier, possibly with attributes, as declarator

Cake generates

```c
int main()
{
  int * p1;
  auto * p2 = p1;
}
```
and warning: auto with pointer is UB in C23

**Comment by gustedt** [comment]
Yes, these are all usages of `auto` that are not foreseen as such in C23. The only possible addition to the `auto` keyword are qualifiers and attributes.

The final goal for C26 or so is to have this the same as C++, but compilers that do `*` or `[]` now, are, for the moment extensions.

If you want to compare this to a working gcc feature, perhaps better use `__auto_type` after which C23 `auto` is (mostly) modelled. I don't think that gcc have finished their implementation of `auto` for C23 mode, yet.

**Comment by thradams** [comment]
This site can be used to see auto in C++
https://cppinsights.io/

**Comment by thradams** [comment]
not used in new backend mode.
