### ISSUE TITLE
duplicated try catch make already used label

### ISSUE THREAD

**Issue by katte** [thradams/cake#4]
If we repeat a try catch block:
#include <stdio.h>
int main()
{
  FILE * f = NULL;
  try
  {
     f = fopen("file.txt", "r");
     if (f == NULL) throw;
    /*success here*/
  }
  catch
  {
     /*some error*/
  }
  if (f)
    fclose(f);

  try
  {
     f = fopen("file.txt", "r");
     if (f == NULL) throw;
    /*success here*/
  }
  catch
  {
     /*some error*/
  }
  if (f)
    fclose(f);
}

The compiled code, in the second try catch block, use the same label causing a compile error.

**Comment by thradams** [comment]
Thanks! 
It has been fixed.
