### ISSUE TITLE
Some transformations on the website are broken

### ISSUE THREAD

**Issue by heatd** [thradams/cake#64]
Hi,

I was trying out http://thradams.com/cake/playground.html but some transformations seem completely broken.

For instance:

- C99 _Bool doesn't work (same output as input, no conversion to uchar)
- C11 _Generic doesn't even compile (no output)

And I'm sure there are more that I missed.

Cool project though, congrats!

**Comment by heatd** [comment]
C99 Hexadecimal floating constants also seems to be broken, and docs conflict whether _Bool would get transformed into unsigned char or int.

**Comment by thradams** [comment]
thanks for the comments.
The problem with _Bool was the options. Compiler was using C99 instead of select C89. Fixed.

Generic is not compiling, the there is no output.

Cake differs from gcc and clang here.
clang and gcc accepts this code, cake not. (probably some lvalue conversion) 
```c
const int * const p;
_Static_assert(_Generic(&p, const int * const * : 1 ), "");
```

**Comment by thradams** [comment]
> C99 Hexadecimal floating constants also seems to be broken, and docs conflict whether _Bool would get transformed into unsigned char or int.

I didn't find the problem in the documentation .Where is it ? (initial versions use to convert to int)

**Comment by thradams** [comment]
I created #65 to fix _Generic.

**Comment by thradams** [comment]
I think everything is fixed, with exception of _Generic that has new issue number.
