### ISSUE TITLE
fop loop initial declarations are not allowed in c89 mode

### ISSUE THREAD

**Issue by madebr** [thradams/cake#77]
c89 does not support variable declarations in the initialization part of a for loop.

The following code is c99+, and c89 incompatible.
```c
void some_function(int* a) {
 for (int i = 0; i < 10; i++) {
   a[i] = i;
 }
}
```

cake should translate this code into (approximately):
```c
void some_function(int* a) {
 {
 int i;
 for (i = 0; i < 10; i++) {
   a[i] = i;
 }
 }
}
```

**Comment by madebr** [comment]
I just read https://github.com/thradams/cake/blob/main/manual.md#c99-transformations.
It looks like this transformation would be not part of the project goals, so feel free to close this issue.

**Comment by thradams** [comment]
Yes this is low priority. 
Before this, what is a list for instance, is compile C99 designed initializers to C89, then the code is compatible with C++ 98.
